# Generated by Django 5.1.6 on 2025-02-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='anime_images/')),
            ],
        ),
    ]
