# Generated by Django 5.1.6 on 2025-02-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_review_dislikes_review_ikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ikes',
            new_name='likes',
        ),
    ]
